// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mapId: __t.string().primaryKey().name("map_id"),
  encounter: __t.u64(),
  hp: __t.f64(),
  maxHp: __t.f64().name("max_hp"),
  respawnAtMicros: __t.u64().name("respawn_at_micros"),
});
