// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  CombatProgressCheckpoint,
} from "./types";

export default {
  streamId: __t.string(),
  sequence: __t.u64(),
  mapId: __t.string(),
  count: __t.u16(),
  get progress() {
    return __t.option(CombatProgressCheckpoint);
  },
};
