import { afterEach, expect, it, vi } from "vitest";
import { parseHTML } from "linkedom";
import { createFullscreenMovementGate } from "./fullscreen-movement";
afterEach(() => vi.useRealTimers());
it("ignores quick openings, suspends once after 700ms, and restores immediately", () => {
  vi.useFakeTimers();
  const apply = vi.fn(), gate = createFullscreenMovementGate(apply);
  gate.setWanted(true);
  gate.setFullscreen(true);
  vi.advanceTimersByTime(699);
  gate.setFullscreen(false);
  vi.advanceTimersByTime(1000);
  expect(apply.mock.calls).toEqual([[true]]);
  gate.setFullscreen(true);
  vi.advanceTimersByTime(350);
  gate.setFullscreen(true);
  vi.advanceTimersByTime(350);
  expect(apply.mock.calls).toEqual([[true], [false]]);
  gate.setFullscreen(true);
  vi.advanceTimersByTime(5000);
  expect(apply).toHaveBeenCalledTimes(2);
  gate.setFullscreen(false);
  expect(apply).toHaveBeenLastCalledWith(true);
  gate.dispose();
});
it("never restores multiplayer if idle expiry or the eye turned it off", () => {
  vi.useFakeTimers();
  const apply = vi.fn(), gate = createFullscreenMovementGate(apply);
  gate.setWanted(true); gate.setFullscreen(true);
  vi.advanceTimersByTime(700);
  gate.setWanted(false); gate.setFullscreen(false);
  expect(apply.mock.calls).toEqual([[true], [false]]);
  gate.dispose();
  expect(vi.getTimerCount()).toBe(0);
});
it("observes overlapping windows, full chat, and native dialog open state", async () => {
  vi.useFakeTimers();
  const { document } = parseHTML('<html><body><div id="inventoryPanel" hidden></div><dialog id="gemShop"></dialog><div id="chatPanel"></div></body></html>');
  const apply = vi.fn(), gate = createFullscreenMovementGate(apply);
  gate.setWanted(true); gate.watchWindows(document);
  const inventory = document.getElementById("inventoryPanel")!, chat = document.getElementById("chatPanel")!, shop = document.getElementById("gemShop")!;
  inventory.hidden = false;
  await Promise.resolve(); vi.advanceTimersByTime(700);
  expect(apply).toHaveBeenLastCalledWith(false);
  shop.setAttribute("open", ""); inventory.hidden = true;
  await Promise.resolve();
  expect(apply).toHaveBeenCalledTimes(2);
  shop.removeAttribute("open"); chat.classList.add("is-large");
  await Promise.resolve();
  expect(apply).toHaveBeenCalledTimes(2);
  chat.classList.remove("is-large"); await Promise.resolve();
  expect(apply).toHaveBeenLastCalledWith(true);
  gate.dispose();
});
