import { expect, it, vi } from "vitest";
import { drawStartingPlayer } from "../game/player-appearance";
import { paintArrowProjectile, paintRockProjectile } from "../game/runtime/weapon-projectile-renderer";
import { simulateGuildBattle } from "../../shared/guild-combat";
import { STARTER_BOW, STARTER_STONE } from "../../shared/items";
import { buildGuildReplayTimeline } from "./guild-replay-timeline";
import { createGuildBattlefieldRenderer } from "./guild-battlefield-renderer";
vi.mock("../game/player-appearance", () => ({ drawStartingPlayer: vi.fn() }));
vi.mock("../game/runtime/weapon-projectile-renderer", () => ({ paintArrowProjectile: vi.fn(), paintRockProjectile: vi.fn() }));
it("uses bounded high-DPI continuous equipment poses and the actual weapon projectile painters", () => {
  const context = new Proxy({}, { get: () => vi.fn(), set: () => true }) as CanvasRenderingContext2D;
  const doc = { defaultView: { devicePixelRatio: 3 }, createElement: () => ({ width: 0, height: 0, getContext: () => context }) };
  const canvas = { ownerDocument: doc, clientWidth: 400, width: 300, height: 150 } as unknown as HTMLCanvasElement;
  const member = (identity: string, weapon: string) => ({ identity, name: identity, fighter: { maxHp: 100, damage: 10, armor: 0, regen: 0, attackRate: 1 }, range: 160, appearance: { rightHandItem: weapon } });
  const timeline = buildGuildReplayTimeline(simulateGuildBattle([member("a", STARTER_BOW)], [member("b", STARTER_STONE), member("c", STARTER_STONE)]));
  const stone = { complete: true, naturalWidth: 26, naturalHeight: 26 } as HTMLImageElement;
  const renderer = createGuildBattlefieldRenderer(canvas, context, timeline, 1, { player: { basicFrontLeg: stone, basicBackLeg: stone, equipment: { [STARTER_STONE]: { sprite: stone } } }, prepare: async () => {}, trees: stone, treeBounds: () => [] });
  for (const shot of timeline.shots.slice(0, 3)) renderer.draw((shot.launch + shot.impact) / 2, true);
  expect(canvas.width).toBe(800); expect(canvas.height).toBe(512);
  expect(vi.mocked(drawStartingPlayer).mock.calls[0][0]).toBe(context);
  expect(vi.mocked(drawStartingPlayer).mock.calls.some(([, , pose]) => pose.smooth && pose.rightHandItem === STARTER_BOW)).toBe(true);
  expect(vi.mocked(drawStartingPlayer).mock.calls.some(([, , pose]) => pose.combatFacing !== 0 && pose.combatFacing !== Math.PI && pose.throwClock! > 0)).toBe(true);
  expect(paintArrowProjectile).toHaveBeenCalled(); expect(paintRockProjectile).toHaveBeenCalled();
  renderer.dispose();
});

it("fits full teams in portrait and landscape while retaining names and numeric HP bars", () => {
  const paintText = vi.fn();
  const context = new Proxy({}, { get: (_target, key) => key === "fillText" ? paintText : vi.fn(), set: () => true }) as CanvasRenderingContext2D;
  const doc = { defaultView: { devicePixelRatio: 2 }, createElement: () => ({ width: 0, height: 0, getContext: () => context }) };
  const canvas = { ownerDocument: doc, clientWidth: 390, clientHeight: 844, width: 0, height: 0 };
  const team = (prefix: string) => Array.from({ length: 20 }, (_, i) => ({ identity: `${prefix}${i}`, name: `${prefix}${i}`, fighter: { maxHp: 100, damage: 0, armor: 0, regen: 0, attackRate: 1 } }));
  const timeline = buildGuildReplayTimeline(simulateGuildBattle(team("A"), team("B")));
  const stone = { naturalWidth: 0 } as HTMLImageElement;
  const renderer = createGuildBattlefieldRenderer(canvas as unknown as HTMLCanvasElement, context, timeline, 20,
    { player: { basicFrontLeg: stone, basicBackLeg: stone, equipment: {} }, prepare: async () => {}, trees: stone, treeBounds: () => [] });
  const portrait = renderer.draw(0, true);
  expect(canvas.width).toBe(780); expect(canvas.height).toBe(1688);
  expect(Math.max(...portrait.slice(0, 20).map(actor => actor.x))).toBeLessThan(Math.min(...portrait.slice(20).map(actor => actor.x)));
  expect(new Set(portrait.slice(0, 20).map(actor => actor.y)).size).toBe(20);
  expect(new Set(portrait.slice(20).map(actor => actor.y)).size).toBe(20);
  expect(portrait.every(actor => actor.x >= 50 && actor.x <= 340 && actor.y >= 150 && actor.y <= 665)).toBe(true);
  expect(paintText.mock.calls.filter(([text]) => text === "100 / 100")).toHaveLength(40);
  for (const fighter of timeline.fighters) expect(paintText.mock.calls.some(([text]) => text === fighter.name)).toBe(true);
  renderer.draw(10, true);
  expect(renderer.draw(0, true)).toEqual(portrait);
  canvas.clientWidth = 844; canvas.clientHeight = 390;
  const landscape = renderer.draw(0, true);
  expect(canvas.width).toBe(1688); expect(canvas.height).toBe(780);
  expect(Math.max(...landscape.slice(0, 20).map(actor => actor.x))).toBeLessThan(Math.min(...landscape.slice(20).map(actor => actor.x)));
  renderer.dispose();
});
