// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as GetChatHistoryProcedure from "../get_chat_history_procedure";
import * as GetGuildHubProcedure from "../get_guild_hub_procedure";
import * as GetGuildReplayProcedure from "../get_guild_replay_procedure";
import * as GetLeaderboardPageProcedure from "../get_leaderboard_page_procedure";
import * as GetLeaderboardWindowProcedure from "../get_leaderboard_window_procedure";
import * as GetModerationHistoryProcedure from "../get_moderation_history_procedure";
import * as GetSocialChatHistoryProcedure from "../get_social_chat_history_procedure";
import * as GetSocialHubProcedure from "../get_social_hub_procedure";
import * as SynchronizeMapShardProcedure from "../synchronize_map_shard_procedure";

export type GetChatHistoryArgs = __Infer<typeof GetChatHistoryProcedure.params>;
export type GetChatHistoryResult = __Infer<typeof GetChatHistoryProcedure.returnType>;
export type GetGuildHubArgs = __Infer<typeof GetGuildHubProcedure.params>;
export type GetGuildHubResult = __Infer<typeof GetGuildHubProcedure.returnType>;
export type GetGuildReplayArgs = __Infer<typeof GetGuildReplayProcedure.params>;
export type GetGuildReplayResult = __Infer<typeof GetGuildReplayProcedure.returnType>;
export type GetLeaderboardPageArgs = __Infer<typeof GetLeaderboardPageProcedure.params>;
export type GetLeaderboardPageResult = __Infer<typeof GetLeaderboardPageProcedure.returnType>;
export type GetLeaderboardWindowArgs = __Infer<typeof GetLeaderboardWindowProcedure.params>;
export type GetLeaderboardWindowResult = __Infer<typeof GetLeaderboardWindowProcedure.returnType>;
export type GetModerationHistoryArgs = __Infer<typeof GetModerationHistoryProcedure.params>;
export type GetModerationHistoryResult = __Infer<typeof GetModerationHistoryProcedure.returnType>;
export type GetSocialChatHistoryArgs = __Infer<typeof GetSocialChatHistoryProcedure.params>;
export type GetSocialChatHistoryResult = __Infer<typeof GetSocialChatHistoryProcedure.returnType>;
export type GetSocialHubArgs = __Infer<typeof GetSocialHubProcedure.params>;
export type GetSocialHubResult = __Infer<typeof GetSocialHubProcedure.returnType>;
export type SynchronizeMapShardArgs = __Infer<typeof SynchronizeMapShardProcedure.params>;
export type SynchronizeMapShardResult = __Infer<typeof SynchronizeMapShardProcedure.returnType>;

